### ISSUE TITLE
Course OPDS feed self link specifies navigation type not acquisition type

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UMCloudDj-Code#16]
OPDS feed for a course as per the OPDS spec should be an acquisition feed; however it's self link shows:

>` <link rel="self" href="/opds/assigned_courses/" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>`

obtained from http://umcloud1.ustadmobile.com/opds/course/?id=http://www.ustadmobile.com/um-tincan/course/IDNUMBER

**Comment by varunasingh** [comment]
assigned_courses is navigation feed because it consists of courses . Courses are acquisition feeds because it consists of assets to acquire.

**Comment by mikedawson** [comment]
Yes assigned courses should be a navigation feed; But this issue is noted on the course OPDS feed; which should be an acquisition feed but is reporting itself to be a navigation feed - e.g. http://umcloud1.ustadmobile.com/opds/course/?id=http://www.ustadmobile.com/um-tincan/course/33
