### ISSUE TITLE
Adjusting usage report and clicking submit does not regenerate report

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UMCloudDj-Code#6]
When viewing a usage report it should be possible to adjust the parameters and click submit to get a new report.  To reproduce select the usage report from the reports menu and generate a report for a group of students.  Change the dates and click submit.  The report does not get regenerated.  Issue observed on Chrome / Ubuntu.

**Comment by varunasingh** [comment]
Root case seems to be statements are not getting classes and schools assigned .
